### PR TITLE
Added tsconfig-paths support.

### PR DESCRIPTION
**Pull request by preda7or**
Hi Sven,
I had some issue with custom paths resolving in my specs and found out that registering tsconfig-paths would help the issue, so I added some lines and it worked for me. I would like to share it with everyone.
Regards,
Gabor

### CODE REVIEW

**Comment by svi3c** [comment]
Hi Gabor,

sorry for the late response. Thanks for the contribution.
Could you add a simple test please?
So I can see it's really working.

Regards,
Sven

**Comment by Laoujin** [comment]
@svi3c : If test(s) are added, would you merge the PR?
I would really like this functionality aswell :)

**Comment by preda7or** [comment]
Sorry guys, had no idea how to test it.
*Stefán Gábor*


Wouter Van Schandevijl <notifications@github.com> ezt írta (időpont: 2019.
febr. 28., Cs, 16:53):

**Comment by ert78gb** [comment]
Is it still a valid feature request?

**Comment by ert78gb** [comment]
I close it because lack of answer

**Pull request closed without merging**
